DOCUMENT_IDS = {
  "0": "1HBPgLziAX2HG9rgtShM1pq2n710qmQi9DLZTZBAU25E",
  "M1": "",
  "M2": "",
  "M3": "",
  "P1": "",
  "P2": "",
  "C1": "",
  "C2": "",
  "A&M": "",
  "EE1": "",
  "EE2": "",
  "B1": "",
  "CS": "",
}